server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
#      server-addr: 127.0.0.1:8848 # 本機部署 nacos位址
      server-addr: nacos:8848 # nacos位址
    gateway:
      routes:
        - id: user-service # router標示，須具有唯一性
          uri: lb://userservice # router的目標位址 lb就是附載均衡，後面跟著server名稱
          predicates: # router判斷式，判斷請求是否符合規則
            - Path=/user/** # 路徑判斷，判斷路徑是否是以/user開頭，如果是則符合規則 有許多規則，自己查API
#            - Before=2022-10-06T21:00:30.433+08:00[Asia/Taipei]
#          filters: # 只針對某個服務加上filter 若要所有router設置要用default filter 定義所有router
#            - AddRequestHeader=truth ,Hello spring cloud! # filter，作用是給每個經過userservice的req header加上：Hello spring cloud!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters: # 定義所有router
          - AddRequestHeader=truth ,Hello spring cloud!