version: "3.8"

services:
  nacos:
    image: zhusaidong/nacos-server-m1:2.0.3
    environment:
      MODE: standalone
    ports:
      - "8848:8848"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "/Users/Damian/mydata/mysql/data:/var/lib/mysql"
      - "/Users/Damian/mydata/mysql/conf:/etc/mysql"
  userservice:
    build: ./user-service
  orderservice:
    build: ./order-service
  gateway:
    build: ./gateway
    ports:
      - "10010:10010"


