server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

# 下面註解，因为在bootstrap.yaml里面这些已经重复了。如果你想测试配置集群名称（部署在HZ或者SH），那就打开这段注释，相应地，注释掉bootstrap.yaml里面全部代码
  application:
    name: userservice   # user的服务名称
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        cluster-name: HZ # 集群名称
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
pattern:
  dateformat: MM-dd HH:mm:ss:SSS


eureka:
  client:
    service-url: # eureka 位址  (eureka 本身也是一個微服務 也要註冊自己)
      defaultZone: http://127.0.0.1:10086/eureka

