server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice   # server name
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: Taipei # 集合名稱
#        namespace: 1acd1a4c-6e50-4173-9e9a-1ad2b85c4dd7 #dev id
#        ephemeral: false

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#    要用eureka 再打開
#eureka:
#  client:
#    service-url: # eureka 位址  (eureka 本身也是一個微服務 也要註冊自己)
#      defaultZone: http://127.0.0.1:10086/eureka
userservice: # 給指定微服務配置負載均衡規則，這裡是userservice服務
  ribbon:
#     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 負載均衡規則
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 負載均衡規則


#ribbon:
#  eager-load:
#    enabled: true # 開啟eager load
#    clients:
#      - userservice # 指定要以該方式load的server (若沒配置 預設為lazy load)
#feign:
#  httpclient:
#    enabled: true # 支援HttpClient的开关
#    max-connections: 200 # 最大連接數
#    max-connections-per-route: 50 # 单个路径的最大連接數
