server:
  port: 10086
spring:
  application:
    name: eurekaServer  # eureka server name
eureka:
  client:
    service-url: # eureka 位址  (eureka 本身也是一個微服務 也要註冊自己)
      defaultZone: http://127.0.0.1:10086/eureka
